name: Deployment
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      #context=step, id=get-filename, key=filename
      script-filename: ${{ steps.get-filename.outputs.filename }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Get Js file name
        run: |
          "JS_FILENAME=$(find ./dist/assets -name '*.js') 
          echo "filename=$JS_FILENAME" >> $GITHUB_OUTPUT"
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Output dist
        run: ls -la
      - name: Output script filename
        run: echo "Script filename is ${{ needs.build.outputs.script-filename }}"
      - name: Deploy to server
        run: echo "Deploying to server..."
