name: Deployment
on:
  push:
    branches:
      - main
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        id: test
        run: npm test
      - name: Report failed tests
        if: failure() && steps.test.outcome == 'failure'
        run: |
          echo "Some tests have failed. Reporting..."
  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: wlaung
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Set up environment variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Set production environment variables"
            echo "${{ secrets.PROD_ENV }}" > .env
          else
            echo "Set development environment variables"
            echo "${{ secrets.DEV_ENV }}" > .env
          fi

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ env.DOCKER_USERNAME }}/myapp:latest \
            -t ${{ env.DOCKER_USERNAME }}/myapp:${{ github.sha }} \
            --push .

  report:
    needs: build
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Report deployment failure
        run: echo "Deployment failed. Please check the logs above for details."
